### ISSUE TITLE
How to Extract the date

### ISSUE THREAD

**Issue by saianwork** [kevin91nl/cryptohist#2]
Hi,

I'm testing your cool lib I managed to do a lot but can't figure how to get the date alone.

example if do 
```
`fetcher = CoinMarketCapFetcher()
symbols=fetcher.get_symbols()

for sym in symbols:
    df_coin =(fetcher.fetch_by_symbol(sym))
    print(df_coin['Close'])`
```

I get this output which makes it impossible to extract Close and dates separately. Can you suggest a solution? many thanks
Date
2013-04-28      134.21
2013-04-29      144.54
2013-04-30      139.00
2013-05-01      116.99
2013-05-02      105.21
2013-05-03       97.75
2013-05-04      112.50
2013-05-05      115.91
2013-05-06      112.30
2013-05-07      111.50

**Comment by saianwork** [comment]
Hi,

I found out sorry for the "non issue" 

Cheers

**Comment by kevin91nl** [comment]
Hi,

Thank you for your reaction. If you have any suggestions for the output of the script, feel free to post it.

Regards,
Kevin
